# 1. PHP Basics — Server-Side Execution

## What is a PHP File?

- A PHP file contains PHP code used to create dynamic web pages.
- It can contain HTML, CSS, JavaScript, and PHP code together in the same file.
- It runs on a web server with PHP installed (e.g., Apache, Nginx), and the output is sent to the browser as plain HTML.
- It is saved with a `.php` extension.

## What Can PHP Do?

- **Generate Dynamic Content** — creates web pages based on user input.
- **Manage Files** — create, open, read, write, and delete files on the server.
- **Process Form Data** — grab and process data submitted through web forms.
- **Handle Cookies** — send and receive cookies to manage sessions.
- **Interact with Databases** — add, delete, and modify data in databases.
- **Control User Access** — manage login systems and user permissions.
- **Encrypt Data** — protect sensitive information for security.

PHP is a **server-side language**. This means a PHP script is executed by a PHP interpreter on the server, and only the *result* is sent to the browser.

## The Request/Response Flow

1. **Request** — A browser sends an HTTP request for a `.php` file (or a route that maps to one).
2. **Execution on the server** — The web server (Apache, Nginx, etc.) hands the file to the PHP interpreter, either via a module like `mod_php` or a process manager like `PHP-FPM`.
  The PHP code runs entirely server-side — loops, database queries, conditionals, includes, whatever the script does.
3. **Output generation** — As the script runs, anything it outputs (via `echo`, `print`, or plain text/HTML outside `<?php ?>` tags) gets assembled into a response body.
4. **Response sent** — The server sends the resulting output — typically HTML, though it could also be JSON, XML, plain text, or an image — back to the browser as the HTTP response.
5. **Browser side** — The browser only ever sees the *output* of the script, never the PHP source code itself. It simply renders the HTML like any other page.

## Example

```php
<!DOCTYPE html>
<html>
<body>
  <h1>Hello, <?php echo $name; ?></h1>
  <p>Today is <?php echo date("Y-m-d"); ?></p>
</body>
</html>
```

The browser never sees `<?php echo $name; ?>`. Instead, it receives something like:

```html
<!DOCTYPE html>
<html>
<body>
  <h1>Hello, Alice</h1>
  <p>Today is 2026-09-12</p>
</body>
</html>
```

## Server-Side vs. Client-Side

This is the key distinction between:

- **Server-side languages** — PHP, Python (Django), Ruby (Rails), Node.js (Express) — which execute on the server before anything reaches the browser.
- **Client-side languages** — JavaScript — which run *in* the browser after being downloaded.

## PHP Tags and Mixed Content

A PHP file can hold different kinds of content — HTML, XML, JSON, plain text, etc. To tell the PHP interpreter which parts are actual PHP code, you wrap them in **PHP tags**: `<?php ... ?>`.

- Anything outside these tags is left untouched and sent straight to the output as-is.
- A PHP code block can be placed anywhere in the document — at the top, in the middle of HTML, or even multiple times throughout the same file.

```php
<h1>Static HTML</h1>
<?php
  // PHP code block — can go anywhere in the file
  echo "<p>This part was generated by PHP.</p>";
?>
<footer>More static HTML</footer>
```

## Statement Termination

PHP requires each statement to be terminated with a semicolon (`;`).

## Case Sensitivity

PHP keywords, functions, classes, and user-defined functions are **not** case-sensitive — `echo`, `ECHO`, and `Echo` all work the same way.
However, **variables ARE case-sensitive** — `$name` and `$Name` are treated as two completely different variables.

```php
ECHO "This works the same as echo"; // ✅ keyword — not case-sensitive

$name = "Alice";
echo $Name; // ❌ Notice: undefined variable — $Name ≠ $name
```
